#_welcome:
    #path:     /
    #defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

get_list:
    path:     _list-posts
    defaults: { _controller: AcmeDemoBundle:Post:getList }
    
create:
    path:   _create-post
    defaults: { _controller: AcmeDemoBundle:Post:create }
    
random:
    path:   _random/{limit}
    defaults: { _controller: AcmeDemoBundle:Post:random }
