Acme\DemoBundle\Entity\Product:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '250'
        price:
            type: integer
        description:
            type: text
    lifecycleCallbacks: {  }
